language: node_js
node_js:
- lts/*
before_install:
- echo "The current branch which is being built -- $TRAVIS_BRANCH"
- git checkout $TRAVIS_BRANCH
- rm -rf ".git"
- cd api
install:
- npm install
- npm run build:dev
script: echo "Skipping NPM Tests!"
cache:
  directories:
  - node_modules
before_deploy:
- cd dist
- git init
- rm local.settings.json
- git add .
- git commit -m "Azure Functions Bot Deployment Commit"
deploy:
- provider: azure_web_apps
  username: $AZ_DEV_SITE_USERNAME
  password: $AZ_DEV_SITE_PASSWORD
  site: $AZ_DEV_SITE_URL
  skip_cleanup: true
  verbose: true
  on:
    branch: dev
- provider: azure_web_apps
  username:
  password: 
  site: 
  skip_cleanup: true
  verbose: true
  on:
    branch: staging
