language: node_js
node_js: 
  - "lts/*"
before_install:
  - rm -rf ".git"
  - cd api
install:
  - npm install
  - npm run build:dev
script: echo "Skipping NPM Tests!"
cache:
  directories:
    - "node_modules"
before_deploy:
  - cd dist
  - git init
  - rm local.settings.json
  - git add .
  - git commit -m "Azure Functions Bot Deployment Commit"
deploy:
  - provider: azure_web_apps
    username:
      secure: "wLI++zG7Ow0FZCuyIloIxoMUw74CnAziT0lpRJD8z+Zh6C38v8GxShtrWF+8ADq/brtQiDF55pVRTe293XTq9s1mAhvIIfoidHq3LCyT6do7c4fhmD87heslH44MY2b0yhFbup3yShhw9qdjCI1Cuk7ZY3HlG+oz04Dr85AtppyJomV6c9OI/dKkzLgRW4UceN9RxHeUJE4EPTNf4vVqX6YrR8rprw17tn9X61DZzywzqgXs5p6gGElU9nKnqJTG4lihpaFibS7BMY1eHe6+IPKxrJBJLDRiltww8x5/hU36gwTHPXKg/cdvVdC7OeRWRYVK0H+gd/L2fTMcLi24avLBOI4ruIbi4FqfF87FfOEwh0HpxbRWXaGXDM8J2T7JBZqyKXEWIAIHdd6g+pG+GRbwghfVGA91x8IbDfX2uBUCbwGe/bciX/2Tq3J7KWW4X9tISeasydpGF1fTH4bARx7NCYWjAzp9ihl1uvTs1j+9ZlD+eXYRKfDqk0GgchThxej0nt3uCsGhbu7eBQkugOCDuPj9urPTfQ/eqhkCHHKvaAVECDot4zrV2pRgCvbcZETik6IDx+QxQOWImdEOLuZ6aeMcFicKUFWhxYZ7Lhlva8nUM32wD1FFS8nCMDGdfJtal1Fp13IzJGsRDD4oVSqtYZZc90ZUO6Mf+O5yIoE="
    password:
      secure: "snddWyfoVMVoA5bfe3LadJBEC70VN0UYZ80D5yzvRQIry1CT96cDs77psw2pZoNRpbJS3EmDwklz1idmb2gFZ2BtxVDxR0x3javkB/cZXFm/KuBvMUVAxT2013XVo6LaAIoKbbPYOWG4ZF69n+A3grvBOxKUEzT/95kXg5S2ozew7kHZCGsv/7GGfh3oFahXkuFvE+oIRBesHS4lP4Y3Cm0FATkNY+sNEPMwXzzZgOZxfYsjzGwu2I4Z1mA9M6Q5nrSXdkDjzoOMX50T2i3BHnJU3hsg8BuAl9ILNpJWFnL/ZGvJxhVtcamYatshkUH3etNKITW/0AuUDc302+hiGbDjpHnQy/MEIomhZqzByt7eDW1zpl3FkJlXFAmAinRomefb452A9KfGOlr8kIOT9/m9Lz1PYnTPudPOn7a5StVLImUQ4USpqEgmHiZo+XkOOvBIiNmWIbVceXtaibUIalJuLlQeJvzV/dxiBWNz0t/soA8+YutO7cY+i80ts2f/2fgRdF0v1gqv8hdON6EIgWb1ZBjAQNp7B0ZlNdHzjjrQceUqtivw/yTOBa2ig8KMFefdu1OckeuO8AGPIPybYCvnIYbAEODieW2MjUXQHnKtXJBb243O/XA5ZJ/hMyWOsAlWNgOD8LQArcuuZ8F0RzgWjAcT3bhK4a1o8cEP9yo="
    site:
      secure: "tZZXpTXQNigJLcAqwvsUkzpbEaUADI0EKWbiZTE0uONnc8LVFLds8vcLymIdlgfXX6CRGZsaT+lv1GwPNslAsJVCcOH118+mBX7sc7PTC5t1G/kau1phWPIozgZ4/pD6ENXhPALSco+uNSpV+9AXl1ciG0RcfS7aAJ964wH7qHdx3YqCdmTDfx77wGvzIaNsnj/08qQ/mzjwlqbn1ZwUX/plpNoJSjPFGxPaVUkjv+D1ze7ctgYSaBtrI5d0Y9yeaBg8Ph4EKqUiT6KR/6GZkj+xSytQr38Bmj+WiuE/37DAiQzcCz9/md6Xpv3iVMwLzyPMSfGraj61xWFA+h/qbNqNNyvVt8DmRkfJeacfYI9tpO+O5T4kJr9eSqJBtVFs4ZhOeA1VuE7AyS5+Vlj6Nho7CW7mgrmI2Rif6VGB4EmsmL/nUJPOXV+OLAORPmgUUl7BX7GsZlpzIs/ZZBffQwEcSQQVh/THCkRaEI0OfPpI/7/oZV381bvYXHJyFjlu+q/sQXJ8JVDv4/xxwDvSo6Ucq0tumShr8w/7MO1gtNze67qRohQj3K3OtNMGsnqORB+17zAWoM8Yde8A0dWsia+Z67ksWKtjdwWc7i2SgmGEEUDUqgVyXDZe+4yF3Tt2VPONSl1jqskEpblzG1MKADFf9NaH3L62xPOGu6+gDIo="
    skip_cleanup: true
    verbose: true
    on:
      branch: dev
  - provider: azure_web_apps
    username:
      secure: "jPjDoUyVq1fFf/nAUUrzxcUSebBusLoTW2a6SM9INtXVAabctJrFPkMY43Dh5d49fCGWWD8OZQcSqDiZfxNe+usOagGOAuoveI6CNBVXaC3AOuiubBIr2ccVh6ut+5zZqveaj827Bg4ehZx8FJU85abiJBi7teYbd6G9o6ypTzwirIoLNs92ck+xMilhhWKd7ASME6/jcqFiOMdyZeZKbaWhtFeg4UkOlxZSkr51LWTGVlwfnQVQCwF4mmgnVDSxGAJoXF1VZazebJQfJvmqjt2Gm5Gcin+eRkGEo0SEHKRSLWn2D/y0Frar9mTjoqTiI5yFXE+gICWP93lbOHf5MDWaGa52+D8avczv/K0+kY6lKTHpYoRJHdDn1ayhcztOVinjvkzKbTYfJle+WOEj8XZEEKOrqlFw701ZSB8kyNi+FbMyvPAGHHkU7iSH4WExJAW+8PcfX2WbJ8CH0R+E7T53Z+9lZgttWn7L9av14TMyVOlwaQ0cEUS2I1HqBDRmpREzqO8H4iSjr98qQtNArhGfDgOm6HUzKRfqnHdzgMGKyzRGzPgb8kPP331HshwgtTaR947qwxOJkIdwYFbRd1BuX2b2vPvERrBL0RJcX/7FvG0g7W3yxfUKTsTz6bOl+b4R45liS+ItzcTVdfnYF74ELNOTzqfL5Cz49/nd5LA="
    password:
      secure: "LU3noo7bNhjIXWRvZ7v5tGKke3Q6nxk73U7wDFzbnZHjM8WpD4KwOjvSMF9nVZiS/qn8dwZ2b0PWZCFE+xPEAtq+N5VFMsItuFLkyg5JlTeXi4vcU2wmgntljzF3T3idJfqZuvD7Gv65KYu6Pwvia3ru0aUannKyroP3f5JEs4n8WzsdFpHEMKEg9epNhfC6RWS8K6P9SgN7cdakvmnybM4VIUFxaAWxoo+U7XUx6eWg825WGCxRMoR7wO2RhBr0nX4rOAKm5iAR1j2ICRgfDtpHpwQQQRbAKLmM1Rd/JQHGjEo1H4inm8WyKKqphTma16xuIuvIb/sDHIJNP0XAX0e3o8S3YkwT0QSHDrXrj831ryWHU0zzUl0OqTQxIBXofDaXgZeopo1cjLWzvVAi4A5iqcmcz25hRnn8A7U78FAAX7X+k0DE3r+2vq4pYvlBA+nAPhYvRZfnDBgOdQDm/LUe5YYoR2KJMAbS1Ml1AEmsTosTh05+Z1Y5AFqGbr6SLBrAiUxHcaX7T8S2wyNxgIiYRwI0mG64rjnUYd7Uvy9iUFwZLA0TUCU5fQoGxRLgLP2ZyvEwlk08qDyFnkEhfP47uAR2cwI38yoTYYFFmAa8vJnpBXh3VEQ6gVLazhxe2G+QOA8X8nq3IKzz1F3Ai9IGAI87MCeqA0wNBY8IjpI="
    site:
      secure: "IHd2gQYnaICkIOkvEInAmWb2wbZdNFexVBPvWhXyLqtQ5/X4VtUr9jh/kqu0Abe7ilSS4kdjpYiLaS8gru2wCWFkScVfPbIp06Dkk6i5ujCLRcbGzM868tUSYCWcKBCRpUBAFguw1mL4WGLhJRIRfajrvTF5WUmFrecZASnSeWwoZlqnbjcmaGjx4HHLGqjTSdoAlccPHkNTszQMaAuzW6dF3U41ParYVE5U3mA2Gs279dmW3jE0vNipUjv/i/PYLEZ2D/Mv/MWedrMWY5lCffBfdVHAyx13MHf6Rv7iqvWXpjjxuwgHj/sB2KqwIsZ3E7Spql59GhaZSMfv4lujivl8ai0yQcL3wYEkgWpp1UZfWZ3paNnzAW/iMqUS8Z/OZPucFmXY4Osfo2qGsgdv4o3JpP2lkyhKC9z4DCn+UV6girGyfApM9T9hecP7UHqy8cddMP40WrhXDIQrMFu3UqaF7T2q/t/y8DNLQ0fmAItE3r9bZ1LQHeW4CGbSMuM7dcwLQT82eOO58Qj2zFzXfbfsTbp0Gvg+3N2IbsAx1JIMHgWei+gd0wtwbl9IOsaQvcFc9V9iro0oRLcjbU7PqTpkJ6GNossMZkUa/2V3cqy/lBs4ztpFtXXz97GqOcEVqkmGE6ZgUxvyaloM8lsuWqjPtu2AbKVosCdoFMyo8aU="
    skip_cleanup: true
    verbose: true
    on:
      branch: staging