language: node_js
node_js:
- lts/*
before_install:
- rm -rf ".git"
- cd api
install:
- npm install
- npm run build:dev
script: echo "Skipping NPM Tests!"
cache:
  directories:
  - node_modules
before_deploy:
- cd dist
- git init
- rm local.settings.json
- git add .
- git commit -m "Azure Functions Bot Deployment Commit"
deploy:
- provider: azure_web_apps
  username: "$AZ_DEV_SITE_USERNAME"
  password: "$AZ_DEV_SITE_PASSWORD"
  site: "$AZ_DEV_SITE_URL"
  skip_cleanup: true
  verbose: true
  on:
    branch: dev
- provider: azure_web_apps
  username:
    secure: jPjDoUyVq1fFf/nAUUrzxcUSebBusLoTW2a6SM9INtXVAabctJrFPkMY43Dh5d49fCGWWD8OZQcSqDiZfxNe+usOagGOAuoveI6CNBVXaC3AOuiubBIr2ccVh6ut+5zZqveaj827Bg4ehZx8FJU85abiJBi7teYbd6G9o6ypTzwirIoLNs92ck+xMilhhWKd7ASME6/jcqFiOMdyZeZKbaWhtFeg4UkOlxZSkr51LWTGVlwfnQVQCwF4mmgnVDSxGAJoXF1VZazebJQfJvmqjt2Gm5Gcin+eRkGEo0SEHKRSLWn2D/y0Frar9mTjoqTiI5yFXE+gICWP93lbOHf5MDWaGa52+D8avczv/K0+kY6lKTHpYoRJHdDn1ayhcztOVinjvkzKbTYfJle+WOEj8XZEEKOrqlFw701ZSB8kyNi+FbMyvPAGHHkU7iSH4WExJAW+8PcfX2WbJ8CH0R+E7T53Z+9lZgttWn7L9av14TMyVOlwaQ0cEUS2I1HqBDRmpREzqO8H4iSjr98qQtNArhGfDgOm6HUzKRfqnHdzgMGKyzRGzPgb8kPP331HshwgtTaR947qwxOJkIdwYFbRd1BuX2b2vPvERrBL0RJcX/7FvG0g7W3yxfUKTsTz6bOl+b4R45liS+ItzcTVdfnYF74ELNOTzqfL5Cz49/nd5LA=
  password:
    secure: LU3noo7bNhjIXWRvZ7v5tGKke3Q6nxk73U7wDFzbnZHjM8WpD4KwOjvSMF9nVZiS/qn8dwZ2b0PWZCFE+xPEAtq+N5VFMsItuFLkyg5JlTeXi4vcU2wmgntljzF3T3idJfqZuvD7Gv65KYu6Pwvia3ru0aUannKyroP3f5JEs4n8WzsdFpHEMKEg9epNhfC6RWS8K6P9SgN7cdakvmnybM4VIUFxaAWxoo+U7XUx6eWg825WGCxRMoR7wO2RhBr0nX4rOAKm5iAR1j2ICRgfDtpHpwQQQRbAKLmM1Rd/JQHGjEo1H4inm8WyKKqphTma16xuIuvIb/sDHIJNP0XAX0e3o8S3YkwT0QSHDrXrj831ryWHU0zzUl0OqTQxIBXofDaXgZeopo1cjLWzvVAi4A5iqcmcz25hRnn8A7U78FAAX7X+k0DE3r+2vq4pYvlBA+nAPhYvRZfnDBgOdQDm/LUe5YYoR2KJMAbS1Ml1AEmsTosTh05+Z1Y5AFqGbr6SLBrAiUxHcaX7T8S2wyNxgIiYRwI0mG64rjnUYd7Uvy9iUFwZLA0TUCU5fQoGxRLgLP2ZyvEwlk08qDyFnkEhfP47uAR2cwI38yoTYYFFmAa8vJnpBXh3VEQ6gVLazhxe2G+QOA8X8nq3IKzz1F3Ai9IGAI87MCeqA0wNBY8IjpI=
  site:
    secure: IHd2gQYnaICkIOkvEInAmWb2wbZdNFexVBPvWhXyLqtQ5/X4VtUr9jh/kqu0Abe7ilSS4kdjpYiLaS8gru2wCWFkScVfPbIp06Dkk6i5ujCLRcbGzM868tUSYCWcKBCRpUBAFguw1mL4WGLhJRIRfajrvTF5WUmFrecZASnSeWwoZlqnbjcmaGjx4HHLGqjTSdoAlccPHkNTszQMaAuzW6dF3U41ParYVE5U3mA2Gs279dmW3jE0vNipUjv/i/PYLEZ2D/Mv/MWedrMWY5lCffBfdVHAyx13MHf6Rv7iqvWXpjjxuwgHj/sB2KqwIsZ3E7Spql59GhaZSMfv4lujivl8ai0yQcL3wYEkgWpp1UZfWZ3paNnzAW/iMqUS8Z/OZPucFmXY4Osfo2qGsgdv4o3JpP2lkyhKC9z4DCn+UV6girGyfApM9T9hecP7UHqy8cddMP40WrhXDIQrMFu3UqaF7T2q/t/y8DNLQ0fmAItE3r9bZ1LQHeW4CGbSMuM7dcwLQT82eOO58Qj2zFzXfbfsTbp0Gvg+3N2IbsAx1JIMHgWei+gd0wtwbl9IOsaQvcFc9V9iro0oRLcjbU7PqTpkJ6GNossMZkUa/2V3cqy/lBs4ztpFtXXz97GqOcEVqkmGE6ZgUxvyaloM8lsuWqjPtu2AbKVosCdoFMyo8aU=
  skip_cleanup: true
  verbose: true
  on:
    branch: staging
env:
  global:
  - secure: Aqi+HnDXAuOmiIBSVsUtUjfOhOJ6ut8c8HqP/GOyy4Wh2lS3N8S0SJVvyXB8sEyAjAYaNjmfJc23pWGmiwZAiE5EQLoarYtAfDGKr4thu0VxbKpmoiTjeaYVcMTWM7LzKcjjZ4kSJvKccldwiarRhN8fW+YDRmZ/3nVguhxANysDTtuUqA4b71CUoBHyQ5xqeoZJqEo0FUHNSONFLowS6+cW8+XR1nEM5hCo1YXQHatez5jhMf8BETLYq26zjBFeLRBpQbyg6baJn8t8P54TVT61WF/9RzWCOHilunm0HEVqKe2nMOvMTIFUfFjusD31gDwcXNWfNJu4YjNeXHPoSI6pt5B+8SetH1FzyyOj6nJb4y9TNZPofLBaVMHyyoaS+YA3SLg7Ewrz+CG4glIP6AGgv8IybqILhQHRLjVTymIF/Iu76z34pKOfr27dqJ+yYWBAm+dHCKjOTMlVpzNS/Mvo2k0d6HnJRNQvOLbp2v7o4EkEqxvfBeJSl93xpOV5SXBUXV9DvOCiUf+e3V/w8mT/xgQV7vY//wizv/ewv9Aog2OKJHd3LCnN8RA1mHVYgvPuoWGfxSHHz/b/loPLck99AFPkaLQpXk5rhI+CF2uMebNSTscG4huAODA12h8Bgfzwnn5eBNXk5D3Cs9L0Iv39a0ktjNkuyelvmNIkUn0=
  - secure: w/TlyU1IznHbf+tZvw+TvbxRiYITwF/NFhvUEwt9CJjZzEYdiKNOvlEUrtSxNqKdMEeFN+cZ9XJxDZU+q1jstHlmjU5Ry7r4INprem8IKXiWGwhFoDSwzmJ2uvuHsG5vuuZIvMTWJKwp1zf6ExVc/TxZ+yasRLV15jBpY8WQhb4ptzGETJ0ivp05Ws74GdIBGZfJDCPRPsysiwScGUGuwJbIjnLSYkawEz12Ihz7cLgJ0zmCDpQk9XHcANT2hgdJcgd44DPIpCKArQyzmq13tjrZPx6vQtddbNLiQYvkjxTZGYzaeIngvYWtxMQdi7TaN4FmpUk3Qm8gCAhlvA45GJXuyUuTUAX8/PSr1Kbuy9y9TJuag7XIKkHBDlRWhqYT9yzaDmUakh2gfu6kE+ygRo2B6M7ld+g8gPxDkz8MFJLCkaOe0YTi2sKTwSeiu9LRETDU3dxY7gulqzHYlHL0Kj5f3vmGdoKXzNKkz80eWogCRTrGNCpkg2+tq9OhuFDnjh44rkjf8gdYopSow+pRig9+22lkBWAR+mVt0/zzjQdSGyUMWVIuNOioclC2gaJ04Y7cvTTFYV/EjRp5GvFwJi/KSWMYP62bWiJI8/IVUhEMPdU7zWKyIumvTn09C4Yth3McsB4QhyT0SF+Hk9jaGpCz6lMR/0Wxz3vIow1lbBc=
  - secure: aKTUmEWfGI2aq34X+4x5GXZ9VPP9HvZfYfZKwHctYyEDRA99c0ETxBcb7yTAQf/NrJuzr+2h0OaZVbHoahltBAl9xAtU6Cmi9PXMUpzF9LyuxRz8/5/S5M1BN3TeRJgItXujrffvBiHUENk2gQyDglWh6eyd6K0Wei9GR44TBzy3YE+b0ZmojS+Dy0SR29Esi9JpLHMJ4RpaLVu7aIDbUd4z2GWCVElKPaoS4ZeWVbiyDTADqXBOTDuNVZd8ePfPvjXEgHKfubKgjecfArriMnEVGP8Pt8lNmwtC+8VQmoOxq5HwGaVwkc0SQ+/AuUQ+aw9idMM8EN4vtmk4nJlqejDIeiIoy1uCO95j+1UTInLsHcAEjLUvM23zkjC7FoWx3ZGFpmHM0heulNVXSr5q9ESoq/ZWbYrPpxoYAPZCvwiFNemEAi62nGwOpIl9FYqdSPereqr7WubPJGf9bFKU+HtrEvYQC5nl93PcJirfy1J/zkJOHKc+HDsfh8+/9opzDEu8iHOnlIN1d+BygJScyuaiZ8X4MCp70EUQKzv/23+uhwjE3PN79400oo0lnEIt5Sj0QpCOsRJcaFeuYbc+edsNNw9+JdqbaSKcY5EXwkt1n3sKD0rPQ3+1aWqmVL3XBNOWWkSRyp/0B3peJRtiHVI6QVr5Lhja7KVOYtQntCs=
