language: node_js
node_js:
- lts/*
before_install:
- echo "The current branch which is being built -- $TRAVIS_BRANCH"
- git checkout $TRAVIS_BRANCH
- rm -rf ".git"
install: npm install
script: 
- npm run build:dev --prefix api
- npm run build:dev --prefix web
- npm run build --prefix api
- npm run build --prefix web
- npm run test:ci --prefix api
cache:
  directories:
  - node_modules
before_deploy:
- cd api/dist
- git init
- git add .
- git commit -m "Azure Functions Bot Deployment Commit"
deploy:
- provider: azure_web_apps
  username: $AZ_DEV_SITE_USERNAME
  password: $AZ_DEV_SITE_PASSWORD
  site: $AZ_DEV_SITE_NAME
  skip_cleanup: true
  verbose: true
  on:
    branch: dev
- provider: azure_web_apps
  username: $AZ_STAGING_SITE_USERNAME
  password: $AZ_STAGING_SITE_PASSWORD
  site: $AZ_STAGING_SITE_NAME
  skip_cleanup: true
  verbose: true
  on:
    branch: staging
- provider: azure_web_apps
  username: $AZ_DEV_SITE_USERNAME
  password: $AZ_DEV_SITE_PASSWORD
  site: $AZ_DEV_SITE_NAME
  skip_cleanup: true
  verbose: true
  on:
    all_branches: true
    condition: $TRAVIS_COMMIT_MESSAGE = deploy-dev && $TRAVIS_EVENT_TYPE = api # event type condition ensures this was manually triggered in travis dashboard ui